openapi: 3.1.0
info:
  title: AI Term Explainer
  description: A plugin that generates explanations of AI/ML terms at three different complexity levels.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /explain:
    post:
      operationId: explainTerm
      summary: Generate explanations of a given AI/ML term at three different complexity levels.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                term:
                  type: string
                  description: The AI/ML term to be explained.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  expert_explanation:
                    type: string
                    description: The explanation of the term for an AI researcher.
                  intermediate_explanation:
                    type: string
                    description: The explanation of the term for a computer science undergraduate.
                  beginner_explanation:
                    type: string
                    description: The explanation of the term for someone with no background in AI or ML.
