openapi: 3.1.0
info:
  title: azki
  description: A plugin that allows the user to generate an image using Fever Dream API.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /generate:
    post:
      operationId: generateImage
      summary: Generate an image using Fever Dream API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image_url:
                  type: string
                  description: The URL of the image to generate.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  job:
                    type: object
